### PR TITLE
Fix HTTP Proxy Connect Command

### PR DESCRIPTION
**Pull request by nimanch**
Based on Connect Command defined here : https://www.rfc-editor.org/rfc/rfc2817#page-6

### CODE REVIEW

**Review by grinay — COMMENTED** [review]
HI. What is actually changed? I can't really see any changes in this PR?

**Comment by nimanch** [comment]
> HI. What is actually changed? I can't really see any changes in this PR?

Hi. There was a ":" missing after the "HOST"

**Comment by grinay** [comment]
Oh, I see now. And see it in docs. Thanks.

**Comment by grinay** [comment]
The package has been published.

**Pull request merged**
